use vtv
SELECT * INTO #CUIT  FROM OPENQUERY(DW,'SELECT CD_PARTY - 20000000000 CD_PARTY, NU_DOCUMENTO FROM TASA.DOCUMENTO_PARTY WHERE CD_TIPO_DOCUMENTO = ''08''')

TRUNCATE TABLE IVR_MOVILES
INSERT INTO IVR_MOVILES

SELECT * FROM (
SELECT distinct CU.NU_DOCUMENTO CUIT, CL.TASA_CLIE_CODIGO CD_PARTY, P.ANI, 'F' TIPO 
FROM CASOS C 
	INNER JOIN CLIENTES CL ON C.SWCUSTOMERID = CL.SWCUSTOMERID 
	INNER JOIN #CUIT CU ON CU.CD_PARTY = CL.TASA_CLIE_CODIGO
	INNER JOIN DW..PARQUE P ON CL.TASA_CLIE_CODIGO = P.CD_PARTY_TITULAR
WHERE 
cctproductoid = 65819 and cctmotivoid = 7 AND CCTSUBMOTIVOID = 4156
AND CL.TASA_TCLI_CODIGO iN ('0R', '0I', '0J')
and c.swdatecreated >= '01/02/2012'



UNION ALL

SELECT DISTINCT p.[CLI numero de identificación tributaria] CUIT, CL.TASA_CLIE_CODIGO CD_PARTY, [CTA NUMERO DE ANI] ANI, 'M' TIPO 
FROM CASOS C 
	INNER JOIN CLIENTES CL ON C.SWCUSTOMERID = CL.SWCUSTOMERID 
	INNER JOIN #CUIT CU ON CU.CD_PARTY = CL.TASA_CLIE_CODIGO
	INNER JOIN vtv..grupo_nivel p on p.[CLI numero de identificación tributaria]  = cu.NU_DOCUMENTO
WHERE 
cctproductoid = 65819 and cctmotivoid = 7 AND CCTSUBMOTIVOID = 4156
AND CL.TASA_TCLI_CODIGO iN ('0R', '0I', '0J')
AND CAST([CTA NUMERO DE ANI] AS BIGINT) >0
and c.swdatecreated >= '01/02/2012'
)A

SELECT * FROM DICTAMINADOS where year(fec_dictamen) = 2012 order by fec_dictamen desc

select * from bcp_dictaminados

select * from 


SELECT * FROM SYSOBJECTS WHERE XTYPE = 'U'