select * from tareas T 
	INNER JOIN ESTADOS E ON T.ID_TAREA = E.ID_TAREA
	INNER JOIN EVENTOS V ON T.ID_EVENTO = V.ID_EVENTS
	
where E.responsables.exist('//RESPONSABLE[./text()="SOPORTE"]')=1
AND CD_EVENTO IN (21,22)

SELECT * FROM CLS_EVENTOS

SELECT *
 FROM EVENTOS V  
	LEFT JOIN ESTADOS E ON V.ID_EVENTO = E.ID_EVENTO 
AND ESTADO IN ('APROBADA','RECHAZADA')
WHERE CD_EVENTO IN (21,22)

SELECT * FROM ESTADOS