SELECT *,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID) THEN 1 ELSE 0 END BO,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'BATISTA') THEN 1 ELSE 0 END BATISTA,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'BENKO') THEN 1 ELSE 0 END BENKO,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'Blanco') THEN 1 ELSE 0 END Blanco,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'COBROS') THEN 1 ELSE 0 END COBROS,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'DSOC') THEN 1 ELSE 0 END DSOC,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'Pernice') THEN 1 ELSE 0 END Pernice,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'POSVENTA') THEN 1 ELSE 0 END POSVENTA,
CASE WHEN EXISTS (SELECT SWOBJECTID FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX WHERE SWOBJECTID = C.SWCASEID AND SUP = 'RECLAMOS') THEN 1 ELSE 0 END RECLAMOS
INTO #T
	FROM VW_CASOS C 
WHERE SWDATECREATED BETWEEN '01/10/2010' AND '31/10/2010' 
AND ISNUMERIC(RIGHT(SWCREATEDBY,1))=1 AND LEN(SWCREATEDBY) < 8

select * from #t


SELECT MAX(SWDATEACTIONTAKEN) FROM INBOX WHERE SWACTIONTAKEN <> 'DIFERIDO'
T INBOX

SELECT DISTINCT SWCREATEDBY  FROM CASOS WHERE LEN(SWCREATEDBY) = 6 AND ISNUMERIC(RIGHT(SWCREATEDBY,1))=1

select * from roster_bo where  SUP = 'COBROS'
SELECT * FROM INBOX I INNER JOIN ROSTER_BO R ON I.SWRECEIVER = R.INBOX

Batista
BENKO
Blanco
COBROS
DSOC
Pernice
POSVENTA
RECLAMOS
SELECT DISTINCT SUP FROM ROSTER_BO