
select * from sys.objects where name like '%90%'

select * from sysdtslog90  order by starttime desc

select * from contacto WHERE SWEMAILADDRESS NOT LIKE '%TELEFONICA%'

SELECT * FROM BCP_REABIERTOS ORDER BY SW


SELECT DISTINCT SWPERSONID FROM CONTACTO
truncate table bcp_reabiertos


SELECT * INTO HOY FROM OPENQUERY(D,'SELECT CU.TASA_CLIE_CODIGO, I.CCTFECHACONTACTO, C.SWCUSTOMERID, C.SWCASEID, I.CCTCASEID, CO.CCTPERSONID
FROM SWBAPPS.SW_CASE C, SWBAPPS.CCT_INSTANCIA I, SWBAPPS.CCT_CONTACTO CO, SWBAPPS.SW_CUSTOMER CU
WHERE C.SWDATECREATED >= TO_DATE(''03/03/2011'',''DD-MM-RR'')
AND CCTFECHACONTACTO >= TO_DATE(''03/03/2011'',''DD-MM-RR'')
 AND C.SWCASEID = I.CCTCASEID
 AND I.CCTCONTACTOID = CO.CCTCONTACTOID
 AND C.SWCUSTOMERID = CU.SWCUSTOMERID')


SELECT * FROM CONTACTO


SELECT YEAR(CCTFECHACONTACTO), MONTH(CCTFECHACONTACTO), SUM(1) FROM INSTANCIAS GROUP BY YEAR(CCTFECHACONTACTO), MONTH(CCTFECHACONTACTO)
ORDER BY YEAR(CCTFECHACONTACTO), MONTH(CCTFECHACONTACTO)

select * from hoy where cctfechacontacto > dbo.dmy(getdate())

SELECT * FROM HOY WHERE SWCUSTOMERID IN (SELECT SWCUSTOMERID FROM CONTACTO)


SELECT * FROM (
SELECT 'REAL' TIPO, H.SWCASEID, C.SWEMAILADDRESS FROM CONTACTO C INNER JOIN HOY H ON C.SWPERSONID = H.CCTPERSONID 
UNION ALL
SELECT 'OTRO' TIPO, H.SWCASEID, C2.SWEMAILADDRESS  FROM HOY H LEFT JOIN CONTACTO C 
	ON C.SWPERSONID = H.CCTPERSONID 
LEFT JOIN CONTACTO C2
	ON H.SWCUSTOMERID = C2.SWCUSTOMERID
WHERE C.SWPERSONID IS NULL
AND C2.SWPERSONID = (SELECT MAX(SWPERSONID) FROM CONTACTO WHERE SWCUSTOMERID = C2.SWCUSTOMERID))a




T CASOS



SELECT * FROM [10.105.8.249].CATE.DBO.E_USUARIOS_J WHERE TIMESTAMP > dbo.dmy(getdate())

