DECLARE @DESDE DATETIME, @HASTA DATETIME, @CUR DATETIME
SELECT @DESDE = '01/04/2012', @HASTA = '25/04/2012'
CREATE TABLE #T (DIA DATETIME)
SET @CUR = @DESDE
WHILE @CUR <= @HASTA
BEGIN
	INSERT INTO #T VALUES(@CUR)
	SET @CUR = DATEADD(DAY,1,@CUR)	
END
SELECT * INTO #T2 FROM #T ,(SELECT DISTINCT TX_PROCESO   FROM DW..ALARMA_LOG)A

SELECT T.*, X.Q INTO #T3 FROM #T2 T LEFT JOIN (
select DBO.DMY(TIMESTAMP) DIA, tx_proceso, SUM(1)Q from dw..alarma_log
where dbo.dmy(timestamp) between @DESDE and @hasta
group by DBO.DMY(TIMESTAMP), tx_proceso)X ON T.DIA = X.DIA AND T.TX_PROCESO = X.TX_PROCESO


DECLARE @DIA VARCHAR(8000)
SELECT @DIA =isnull(@DIA + ',[' + convert(varchar,DIA,103) + ']','[' + convert(varchar,DIA,103)+ ']')
FROM #T3 GROUP BY DIA ORDER BY DIA
exec('select * from #T3 T pivot (sum (Q) for DIA in ('+ @DIA +')) P')

DROP TABLE #T
DROP TABLE #T2
DROP TABLE #T3


-----

DECLARE @ANIO SMALLINT, @CUR TINYINT, @HASTA TINYINT
SET @ANIO = 2012
CREATE TABLE #T (mes TINYINT)
SET @CUR = 1
SELECT @HASTA = CASE WHEN @ANIO = YEAR(GETDATE())  THEN MONTH(GETDATE()) ELSE 12 END

WHILE @CUR <= @HASTA
BEGIN
	INSERT INTO #T VALUES(@CUR)
	SET @CUR = @CUR +1
END
SELECT * INTO #T2 FROM #T ,(SELECT DISTINCT TX_PROCESO   FROM DW..ALARMA_LOG)A

SELECT T.*, X.Q INTO #T3 FROM #T2 T LEFT JOIN (
select MONTH(TIMESTAMP) MES, tx_proceso, COUNT(DISTINCT DBO.DMY(TIMESTAMP))Q from dw..alarma_log
where timestamp >= '01/04/2012'
group by MONTH(TIMESTAMP), tx_proceso)X ON T.MES = X.MES AND T.TX_PROCESO = X.TX_PROCESO


DECLARE @MES VARCHAR(8000)
SELECT @MES =isnull(@MES + ',[' + convert(varchar,MES,103) + ']','[' + convert(varchar,MES,103)+ ']')
FROM #T3 GROUP BY MES ORDER BY MES
exec('select * from #T3 T pivot (sum (Q) for MES in ('+ @MES +')) P')

DROP TABLE #T
DROP TABLE #T2
DROP TABLE #T3